[package]
name = "grt"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# reqwest = {version = "0.11.11", features=["blocking"]}
json = "0.12.4"
skim = "0.9.4"
getopts = "0.2"
