name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-20.04"

    steps:
      - uses: actions/checkout@v3

      - name: "Build"
        run: cargo build

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: target/debug/grt
